name: Update Chrome Extension

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: |
          npm run build

      - name: Build
        run: |-
          zip -r chrome-extension-${{ github.event.head_commit.id }}.zip dist

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.event.head_commit.id }}.zip

  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      EXTENSION_ID: nmdhmjebjhcfbjnmdidhngldanikalje

    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: |-
          chrome-webstore-upload upload \\
            --source chrome-extension-${{ github.event.head_commit.id }}.zip \\
            --extension-id ${{ env.EXTENSION_ID }} \\
            --client-id ${{ secrets.WEBSTORE_CLIENT_ID }} \\
            --client-secret ${{ secrets.WEBSTORE_CLIENT_SECRET }} \\
            --refresh-token ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
